# Generated by Django 5.1 on 2024-10-22 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpleadosApp', '0002_employee_delete_empleados'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Empleados',
        ),
    ]
